### ISSUE TITLE
How to train models from scratch in real data?

### ISSUE THREAD

**Issue by Yushu-Li** [harshays/inputgradients#1]
Thanks to the fantastic work you made. I want to train the models from scratch in real data. But it seems that there is something missing in "01_fig_in_real_data.ipynb", which makes "1.3  Training models from scratch" can't link to a correct place. I would be grateful if you could provide the training code.

**Comment by harshays** [comment]
Hi Yushu, the codebase has not been updated. I am currently working on updating the code & notebooks, and should be done in ~2 weeks. I will include the scripts to train the models in the updated version.
